# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Wed Aug 14 06:23:15 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 448)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 57, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnAllowAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnAllowAll.setGeometry(QtCore.QRect(460, 80, 131, 23))
        self.btnAllowAll.setObjectName("btnAllowAll")
        self.btnAllow = QtWidgets.QPushButton(self.centralwidget)
        self.btnAllow.setGeometry(QtCore.QRect(460, 110, 131, 23))
        self.btnAllow.setObjectName("btnAllow")
        self.btnBlock = QtWidgets.QPushButton(self.centralwidget)
        self.btnBlock.setGeometry(QtCore.QRect(460, 140, 131, 23))
        self.btnBlock.setObjectName("btnBlock")
        self.btnConfigDefault = QtWidgets.QPushButton(self.centralwidget)
        self.btnConfigDefault.setGeometry(QtCore.QRect(460, 350, 131, 23))
        self.btnConfigDefault.setObjectName("btnConfigDefault")
        self.tblClients = QtWidgets.QTableWidget(self.centralwidget)
        self.tblClients.setEnabled(True)
        self.tblClients.setGeometry(QtCore.QRect(20, 80, 431, 291))
        self.tblClients.setAccessibleDescription("")
        self.tblClients.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblClients.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblClients.setObjectName("tblClients")
        self.tblClients.setColumnCount(4)
        self.tblClients.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tblClients.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblClients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblClients.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblClients.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblClients.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblClients.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblClients.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblClients.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblClients.setItem(0, 3, item)
        self.tblClients.horizontalHeader().setCascadingSectionResizes(False)
        self.tblClients.horizontalHeader().setStretchLastSection(True)
        self.tblClients.verticalHeader().setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Clients", None, -1))
        self.btnAllowAll.setText(QtWidgets.QApplication.translate("MainWindow", "Allow Always", None, -1))
        self.btnAllow.setText(QtWidgets.QApplication.translate("MainWindow", "Allow", None, -1))
        self.btnBlock.setText(QtWidgets.QApplication.translate("MainWindow", "Block", None, -1))
        self.btnConfigDefault.setText(QtWidgets.QApplication.translate("MainWindow", "Default Blacklist", None, -1))
        self.tblClients.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.tblClients.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Computer Name", None, -1))
        self.tblClients.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "IP Address", None, -1))
        self.tblClients.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Status", None, -1))
        self.tblClients.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Default Blacklist", None, -1))
        __sortingEnabled = self.tblClients.isSortingEnabled()
        self.tblClients.setSortingEnabled(False)
        self.tblClients.item(0, 0).setText(QtWidgets.QApplication.translate("MainWindow", "PC1", None, -1))
        self.tblClients.item(0, 1).setText(QtWidgets.QApplication.translate("MainWindow", "192.168.1.5", None, -1))
        self.tblClients.item(0, 2).setText(QtWidgets.QApplication.translate("MainWindow", "ONLINE", None, -1))
        self.tblClients.item(0, 3).setText(QtWidgets.QApplication.translate("MainWindow", "UPDATED", None, -1))
        self.tblClients.setSortingEnabled(__sortingEnabled)

